# vi: set sw=2 ts=2:
# Perform additional server setup
---

- name: apt | Install additional python packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - python-software-properties
    - python-virtualenv
    - python-dev

- name: ufw | Enable HTTP connections for the web server
  ufw: rule=allow port=80

- name: ufw | Enable HTTPS connections for the web server
  ufw: rule=allow port=443

- name: ufw | Reload firewall
  ufw: state=reloaded

