# vi: set sw=2 ts=2:
# Uwsgi related tasks (install uwsgi, setup path for vessals and sockets)
---

- name: Install uwsgi with pip
  sudo: yes
  pip: name=uwsgi

- name: Assures uwsgi sites dir exists
  file: path=/etc/uwsgi/sites state=directory

- name: Assures uwsgi socket dir exists
  file: path=/var/uwsgi state=directory
        owner={{ deploy_user }} group=www-data

- name: Create uwsgi Upstart script
  template: src=uwsgi.conf.tpl dest=/etc/init/uwsgi.conf
